import matter from "gray-matter";
import { readFileSync, writeFileSync, readdirSync, statSync } from "fs";
import { join, relative, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const CANDIDATES_DIR = join(__dirname, "..");
const README_PATH = join(CANDIDATES_DIR, "README.md");

const STAGE_ORDER = [
  "sourced",
  "culture_screen",
  "short_circuit",
  "technical",
  "closing",
  "offer",
  "hired",
  "rejected",
] as const;

type Stage = (typeof STAGE_ORDER)[number];

interface Candidate {
  name: string;
  role: string;
  stage: Stage;
  source: string;
  applied_date: string;
  filePath: string;
}

function findCandidateFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    if (entry === "scripts" || entry === "TEMPLATE.md" || entry === "README.md")
      continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      files.push(...findCandidateFiles(full));
    } else if (entry.endsWith(".md")) {
      files.push(full);
    }
  }
  return files;
}

function formatDate(val: unknown): string {
  if (!val) return "—";
  if (val instanceof Date) {
    return val.toISOString().split("T")[0];
  }
  return String(val);
}

function parseCandidates(): Candidate[] {
  const files = findCandidateFiles(CANDIDATES_DIR);
  const candidates: Candidate[] = [];

  for (const file of files) {
    const raw = readFileSync(file, "utf-8");
    const { data } = matter(raw);
    if (!data.name || !data.role || !data.stage) continue;

    candidates.push({
      name: data.name,
      role: data.role,
      stage: data.stage,
      source: data.source || "—",
      applied_date: formatDate(data.applied_date),
      filePath: relative(CANDIDATES_DIR, file),
    });
  }

  return candidates;
}

function stageLabel(s: Stage): string {
  return s
    .split("_")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");
}

function roleLabel(r: string): string {
  return r
    .split("-")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");
}

function generate() {
  const candidates = parseCandidates();

  const active = candidates.filter(
    (c) => c.stage !== "rejected" && c.stage !== "hired"
  );
  const roles = [...new Set(candidates.map((c) => c.role))].sort();

  const lines: string[] = [
    "# Candidate Pipeline",
    "",
    `> **${active.length} active** candidate${active.length !== 1 ? "s" : ""} across ${new Set(active.map((c) => c.role)).size} role${new Set(active.map((c) => c.role)).size !== 1 ? "s" : ""}`,
    "",
    "*Auto-generated by `npx tsx docs/candidates/scripts/pipeline.ts`*",
    "",
    "---",
    "",
  ];

  for (const role of roles) {
    const roleCandidates = candidates
      .filter((c) => c.role === role)
      .sort(
        (a, b) =>
          STAGE_ORDER.indexOf(a.stage) - STAGE_ORDER.indexOf(b.stage)
      );

    lines.push(`## ${roleLabel(role)}`);
    lines.push("");
    lines.push("| Candidate | Stage | Source | Date | File |");
    lines.push("|-----------|-------|--------|------|------|");

    for (const c of roleCandidates) {
      lines.push(
        `| ${c.name} | ${stageLabel(c.stage)} | ${c.source} | ${c.applied_date} | [${c.name.split(" ")[0].toLowerCase()}](${c.filePath}) |`
      );
    }

    lines.push("");
  }

  writeFileSync(README_PATH, lines.join("\n"));
  console.log(`Pipeline README written to ${README_PATH}`);
  console.log(`  ${candidates.length} candidates, ${active.length} active`);
}

generate();
